import { StyleSheet } from "react-native";
import {
  colors,
  typography,
  spacing,
  borderRadius,
} from "../../public/styles/global";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  bgImage: { flex: 1, width: "100%", height: "100%" },
  bgImageStyle: { opacity: 0.6 },
  header: {
    paddingTop: 40,
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.textInverse,
    letterSpacing: 2,
  },
  headerSubtitle: {
    fontSize: 12,
    color: colors.textInverse,
    opacity: 0.8,
  },
  list: { padding: spacing.md, paddingTop: spacing.lg },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 5,
    padding: spacing.lg,
    marginBottom: spacing.md,
    shadowColor: "grey",
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.4,
    shadowRadius: 30,
    elevation: 8,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  authorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  authorName: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  cardDate: { ...typography.caption, color: colors.textMuted },
  cardTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  cardBody: { ...typography.body, color: colors.textSecondary, lineHeight: 22 },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  deleteBtn: {
    padding: 4,
  },
  deleteIcon: {
    fontSize: 16,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  reactionsRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  reactionBtn: {
    padding: 6,
    backgroundColor: colors.background,
    borderRadius: 8,
  },
  reactionEmoji: {
    fontSize: 16,
  },
  reactionCount: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    backgroundColor: colors.background,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
  },
  reactionNum: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: "600",
  },
  expiryBadge: {
    backgroundColor: colors.warning + "20",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  expiryText: {
    fontSize: 11,
    color: colors.warning,
    fontWeight: "600",
  },
  reactionOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
  },
  reactionBubble: {
    position: "absolute",
    bottom: 10,
    left: 16,
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: spacing.sm,
    gap: spacing.xs,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  reactionBubbleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  reactionBubbleEmoji: {
    fontSize: 20,
  },
  fab: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.xl,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.info,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  fabText: { fontSize: 28, color: colors.textInverse },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xxl,
  },
  emptyEmoji: { fontSize: 64, marginBottom: spacing.md },
  emptyText: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: "center",
  },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "flex-end",
  },
  content: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.lg,
    paddingTop: spacing.xl,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: spacing.lg,
  },
  title: {
    ...typography.h2,
    color: colors.textPrimary,
    marginBottom: spacing.lg,
  },
  input: {
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...typography.body,
    color: colors.textPrimary,
  },
  textArea: { height: 120, textAlignVertical: "top" },
  colorLabel: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  colorRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  colorBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  colorPlain: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    position: "relative",
    overflow: "hidden",
  },
  colorActive: {
    borderWidth: 3,
    borderColor: colors.textPrimary,
  },
  expiryRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  expiryLabel: {
    ...typography.body,
    color: colors.textSecondary,
  },
  expiryInput: {
    width: 60,
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    textAlign: "center",
    ...typography.body,
    color: colors.textPrimary,
  },
  bgToggle: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  bgToggleBtn: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
  },
  bgToggleActive: {
    borderColor: colors.info,
    backgroundColor: colors.info + "15",
  },
  bgToggleText: {
    ...typography.bodySmall,
    color: colors.textMuted,
    fontWeight: "600",
  },
  bgToggleTextActive: {
    color: colors.info,
  },
  imagePickWrap: {
    marginBottom: spacing.md,
  },
  imagePickBtn: {
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: "dashed",
    alignItems: "center",
  },
  imagePickText: {
    ...typography.body,
    color: colors.info,
    fontWeight: "600",
  },
  imagePreview: {
    width: "100%",
    height: 120,
    borderRadius: borderRadius.md,
    marginTop: spacing.sm,
  },
  previewWrap: {
    marginBottom: spacing.md,
  },
  previewLabel: {
    ...typography.caption,
    color: colors.textMuted,
    marginBottom: spacing.xs,
  },
  previewCard: {
    backgroundColor: colors.background,
    borderRadius: 12,
    padding: spacing.md,
    overflow: "hidden",
    position: "relative",
  },
  previewBgImg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 12,
    opacity: 0.7,
  },
  previewTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginBottom: 4,
  },
  previewBody: {
    ...typography.bodySmall,
    color: colors.textSecondary,
  },
  button: {
    backgroundColor: colors.info,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    alignItems: "center",
    marginTop: spacing.md,
    marginBottom: spacing.xl,
  },
  buttonText: { ...typography.button, color: colors.textInverse },
});

export const detailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f0f0",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0f0f0",
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.md,
  },
  headerTitle: {
    flex: 1,
    fontSize: 15,
    fontFamily: "PilotCommand",
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  bannerImg: {
    width: "100%",
    height: 240,
  },
  content: {
    padding: spacing.lg,
    paddingTop: spacing.xl,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#1a1a1a",
    lineHeight: 34,
    marginBottom: spacing.lg,
  },
  authorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  authorName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#333",
  },
  date: {
    fontSize: 12,
    color: "#999",
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginVertical: spacing.lg,
  },
  body: {
    fontSize: 16,
    color: "#444",
    lineHeight: 28,
    letterSpacing: 0.2,
  },
});
