import { StyleSheet } from "react-native";
import {
  colors,
  typography,
  spacing,
  borderRadius,
} from "../../public/styles/global";

export const programStyles = StyleSheet.create({
  container: { flex: 1 },
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xl,
  },
  loadingText: { ...typography.body, color: colors.textMuted },
  emptyEmoji: { fontSize: 64, marginBottom: spacing.md },
  emptyTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    textAlign: "center",
  },
  emptySubtitle: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: "center",
    marginTop: spacing.sm,
  },
  createBtn: {
    marginTop: spacing.xl,
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: borderRadius.lg,
  },
  createBtnText: {
    ...typography.body,
    color: colors.textInverse,
    fontWeight: "600",
  },
  usersList: { padding: spacing.md, paddingBottom: 100 },
  userCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.sm,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    minHeight: 72,
    overflow: "visible",
  },
  userAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary + "15",
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
  },
  avatarEmoji: { fontSize: 22 },
  userDetails: { flex: 1 },
  userCardName: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "600",
  },
  userCardCount: { ...typography.caption, color: colors.textMuted },
  userReactions: {
    position: "absolute",
    bottom: -8,
    right: 12,
    flexDirection: "row",
    gap: 4,
  },
  userReactionBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  userReactionEmoji: { fontSize: 16 },
  userReactionCount: { fontSize: 12, color: colors.textMuted, marginLeft: 3 },
  chevron: { fontSize: 20, color: colors.textMuted },
  emptyList: { padding: spacing.xl, alignItems: "center" },
  emptyListText: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: "center",
  },
  fab: {
    position: "absolute",
    bottom: 90,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  fabText: {
    fontSize: 28,
    color: colors.textInverse,
    fontWeight: "300",
    marginTop: -2,
  },
  unifiedHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
  },
  headerAvatar: {
    marginRight: spacing.sm,
  },
  backArrow: {
    fontSize: 20,
    color: colors.textInverse,
  },
  headerInfo: {
    flex: 1,
  },
  headerTitle: {
    color: colors.textInverse,
    fontSize: 16,
    fontFamily: "PilotCommand",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  headerSubtitle: {
    ...typography.caption,
    color: "rgba(255,255,255,0.7)",
  },
  shareBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  shareBtnText: {
    fontSize: 16,
  },
  continueOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.lg,
  },
  continueModal: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: spacing.xl,
    width: "100%",
    maxWidth: 320,
    alignItems: "center",
  },
  continueTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
    textAlign: "center",
  },
  continueText: {
    ...typography.body,
    color: colors.textMuted,
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  continueBtn: {
    width: "100%",
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  continueBtnText: {
    ...typography.body,
    color: colors.textInverse,
    fontWeight: "600",
  },
  continueBtnSecondary: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: colors.border,
  },
  continueBtnTextSecondary: {
    ...typography.body,
    color: colors.textMuted,
    fontWeight: "600",
  },
});

export const userDetailStyles = StyleSheet.create({
  prayersList: { padding: spacing.md, paddingBottom: 100 },
  prayerCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    overflow: "visible",
  },
  prayerUrgent: {},
  prayerText: {
    ...typography.body,
    color: colors.textPrimary,
    lineHeight: 22,
    fontSize: 15,
  },
  readMoreBtn: {
    color: colors.info,
    fontWeight: "600",
  },
  moodBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: spacing.sm,
  },
  moodTagImage: {
    width: 16,
    height: 16,
    resizeMode: "contain",
  },
  moodText: { fontSize: 12, color: "#858484", fontWeight: "500" },
  reactionsDisplay: {
    position: "absolute",
    bottom: -10,
    right: 10,
    flexDirection: "row",
    gap: 4,
  },
  reactionCount: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  reactionEmoji: { fontSize: 16 },
  reactionNum: { fontSize: 12, color: colors.textMuted, marginLeft: 3 },
  reactionOverlayContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  reactionBubble: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 28,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  reactionBubbleBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  reactionBubbleEmoji: {
    fontSize: 28,
  },
  popupOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  reactorsPopup: {
    position: "absolute",
    width: 220,
    maxHeight: 280,
    backgroundColor: colors.surface,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
    overflow: "hidden",
  },
  popupHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.sm,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  popupTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  popupTitle: {
    ...typography.bodySmall,
    color: colors.textPrimary,
    fontWeight: "600",
    marginRight: spacing.sm,
  },
  popupTotalBadge: {
    flexDirection: "row",
    gap: 6,
  },
  popupTotalItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  popupTotalEmoji: {
    fontSize: 14,
  },
  popupTotalNum: {
    fontSize: 12,
    color: colors.textMuted,
    marginLeft: 2,
  },
  popupClose: {
    fontSize: 18,
    color: colors.textMuted,
    padding: 4,
  },
  popupScroll: {
    maxHeight: 240,
  },
  popupRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border + "40",
  },
  popupAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary + "15",
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.sm,
  },
  popupAvatarEmoji: {
    fontSize: 14,
  },
  popupName: {
    flex: 1,
    ...typography.bodySmall,
    color: colors.textPrimary,
  },
  popupReactionEmoji: {
    fontSize: 18,
  },
  popupEmpty: {
    textAlign: "center",
    padding: spacing.md,
    color: colors.textMuted,
    ...typography.bodySmall,
  },
});

export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  modalTitle: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  closeBtn: { fontSize: 24, color: colors.textMuted },
  sectionLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
    marginTop: spacing.xs,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "600",
  },
  predicatorsList: { marginBottom: spacing.lg, maxHeight: 200 },
  noPredicators: {
    ...typography.caption,
    color: colors.textMuted,
    fontStyle: "italic",
    padding: spacing.md,
  },
  predicatorRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.sm,
    borderWidth: 2,
    borderColor: "transparent",
  },
  predicatorSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary + "10",
  },
  predicatorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary + "20",
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
  },
  predicatorAvatarText: { fontSize: 20 },
  predicatorName: { ...typography.body, color: colors.textPrimary, flex: 1 },
  checkMark: { fontSize: 20, color: colors.primary, fontWeight: "bold" },

  // Textarea wrapper cu counter integrat
  textareaWrapper: {
    position: "relative",
    marginBottom: spacing.md,
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    paddingBottom: spacing.xl + 8,
    minHeight: 140,
    ...typography.body,
    color: colors.textPrimary,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: colors.border,
  },
  charCountInside: {
    position: "absolute",
    bottom: 10,
    right: 12,
    fontSize: 11,
    color: "#6b7280",
    fontWeight: "500",
  },
  charCount: {
    ...typography.caption,
    color: colors.textMuted,
    textAlign: "right",
    marginBottom: spacing.md,
  },

  // Toggle urgent modern cu BulbToggle
  urgentToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "transparent",
    paddingVertical: 8,
    marginBottom: spacing.md,
  },
  urgentLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  urgentTagImage: {
    width: 18,
    height: 18,
    marginRight: 10,
    resizeMode: "contain",
  },
  urgentLabel: {
    fontSize: 14,
    color: colors.textMuted,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  urgentLabelActive: {
    color: colors.error,
    fontWeight: "700",
  },

  optionBtn: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: "transparent",
  },
  optionUrgent: {
    borderColor: colors.error,
    backgroundColor: colors.error + "10",
  },
  optionEmoji: { fontSize: 20, marginRight: spacing.sm },
  optionText: { ...typography.body, color: colors.textPrimary },
  optionTextActive: { fontWeight: "600", color: colors.error },

  // Mood buttons moderne
  moodsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: spacing.lg,
  },
  moodBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  moodActive: {
    backgroundColor: colors.success,
    borderColor: colors.success,
    shadowColor: colors.success,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  moodBtnText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  moodText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  moodTextActive: {
    color: colors.textInverse,
    fontWeight: "600",
  },

  // Buton Adaugă - success, dreapta jos
  submitRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: spacing.xs,
  },
  submitBtn: {
    backgroundColor: colors.success,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 10,
    alignItems: "center",
    shadowColor: colors.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  submitDisabled: { opacity: 0.5 },
  submitText: {
    fontSize: 14,
    color: colors.textInverse,
    fontWeight: "600",
  },
});
