import { StyleSheet } from "react-native";
import {
  colors,
  typography,
  spacing,
  borderRadius,
} from "../../public/styles/global";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  screenBg: { flex: 1, backgroundColor: "#f0f0f0" },
  gradientHeader: {
    paddingTop: 40,
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  gradientHeaderTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.textInverse,
    letterSpacing: 2,
  },
  list: { padding: spacing.md, paddingTop: spacing.lg },
  gameCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    marginBottom: spacing.md,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  gameGradient: { padding: spacing.xl, alignItems: "center" },
  gameEmoji: { fontSize: 56, marginBottom: spacing.md },
  gameName: {
    ...typography.h2,
    color: colors.textPrimary,
    textAlign: "center",
    marginBottom: spacing.xs,
  },
  gameDescription: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: spacing.lg,
  },
  gameStats: { flexDirection: "row", gap: spacing.lg },
  stat: { alignItems: "center" },
  statValue: { ...typography.h3, color: colors.primary, fontWeight: "700" },
  statLabel: { ...typography.caption, color: colors.textMuted },
  playButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xxl,
    borderRadius: borderRadius.full,
    marginTop: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  playButtonText: {
    ...typography.button,
    color: colors.textInverse,
    marginLeft: spacing.sm,
  },
  multiplayerBadge: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
    backgroundColor: colors.secondary,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.full,
  },
  multiplayerText: {
    ...typography.caption,
    color: colors.textInverse,
    fontWeight: "600",
  },
});

export const quizStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.xl,
    marginTop: 40,
  },
  progress: { ...typography.body, color: colors.textSecondary },
  score: { ...typography.h3, color: colors.primary },
  questionCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    marginBottom: spacing.xl,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  questionText: {
    ...typography.h2,
    color: colors.textPrimary,
    textAlign: "center",
  },
  optionsContainer: { gap: spacing.md },
  option: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    alignItems: "center",
  },
  optionSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary + "10",
  },
  optionCorrect: {
    borderColor: colors.success,
    backgroundColor: colors.success + "15",
  },
  optionWrong: {
    borderColor: colors.error,
    backgroundColor: colors.error + "15",
  },
  optionText: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "500",
  },
  resultContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xl,
    backgroundColor: colors.background,
  },
  resultEmoji: { fontSize: 80, marginBottom: spacing.lg },
  resultTitle: {
    ...typography.h1,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  resultScore: {
    ...typography.h2,
    color: colors.primary,
    marginBottom: spacing.xl,
  },
  backButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xxl,
    borderRadius: borderRadius.full,
  },
  backButtonText: { ...typography.button, color: colors.textInverse },
});

export const leaderboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loadingContainer: { flex: 1, alignItems: "center", justifyContent: "center" },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 50,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  backText: {
    ...typography.body,
    color: colors.textInverse,
    marginBottom: spacing.md,
  },
  headerTitle: { ...typography.h1, color: colors.textInverse },
  headerSubtitle: {
    ...typography.body,
    color: colors.textInverse,
    opacity: 0.85,
  },
  list: { padding: spacing.md },
  row: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  topRow: { backgroundColor: colors.primary + "10" },
  rankContainer: { width: 50, alignItems: "center" },
  rank: { fontSize: 24 },
  playerInfo: { flex: 1, marginLeft: spacing.md },
  playerName: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "600",
  },
  scoreContainer: { alignItems: "flex-end" },
  score: { ...typography.h3, color: colors.primary, fontWeight: "700" },
  scoreLabel: { ...typography.caption, color: colors.textMuted },
  emptyContainer: { alignItems: "center", padding: spacing.xxl },
  emptyEmoji: { fontSize: 64, marginBottom: spacing.md },
  emptyText: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: "center",
  },
});

export const memoryStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 40,
    marginBottom: spacing.xl,
  },
  reference: { ...typography.h2, color: colors.primary },
  stats: { flexDirection: "row", gap: spacing.md },
  timer: { ...typography.body, color: colors.error },
  scoreText: { ...typography.body, color: colors.textPrimary },
  selectedArea: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    minHeight: 150,
    marginBottom: spacing.lg,
  },
  shuffledArea: { flex: 1 },
  areaLabel: {
    ...typography.bodySmall,
    color: colors.textMuted,
    marginBottom: spacing.md,
  },
  wordsRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  wordChip: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.full,
  },
  selectedChip: { backgroundColor: colors.success },
  wordText: { ...typography.body, color: colors.textInverse },
  feedback: {
    position: "absolute",
    bottom: 100,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  feedbackText: { ...typography.h2, color: colors.textPrimary },
  resultContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  resultEmoji: { fontSize: 80, marginBottom: spacing.lg },
  resultTitle: { ...typography.h1, color: colors.textPrimary },
  resultScore: {
    ...typography.h2,
    color: colors.primary,
    marginBottom: spacing.xl,
  },
  backButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xxl,
    borderRadius: borderRadius.full,
  },
  backButtonText: { ...typography.button, color: colors.textInverse },
});

export const lobbyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
    paddingTop: 60,
  },
  title: { ...typography.h1, color: colors.textPrimary, textAlign: "center" },
  subtitle: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    marginBottom: spacing.md,
  },
  buttonText: { ...typography.button, color: colors.textInverse },
  buttonSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.primary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    alignItems: "center",
  },
  buttonSecondaryText: { ...typography.button, color: colors.primary },
  divider: { alignItems: "center", marginVertical: spacing.lg },
  dividerText: { ...typography.body, color: colors.textMuted },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    ...typography.body,
    marginBottom: spacing.md,
  },
  playerList: { flex: 1, marginVertical: spacing.lg },
  playerRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.sm,
  },
  playerEmoji: { fontSize: 24, marginRight: spacing.md },
  playerName: { ...typography.body, color: colors.textPrimary, flex: 1 },
  playerScore: { ...typography.body, color: colors.primary },
  waitText: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: "center",
    marginVertical: spacing.lg,
  },
  backBtn: { alignItems: "center", marginTop: spacing.lg },
  backText: { ...typography.body, color: colors.primary },
  leaveBtn: {
    alignItems: "center",
    paddingVertical: spacing.md,
    marginTop: spacing.md,
  },
  leaveText: { ...typography.button, color: colors.error },
});
