import { StyleSheet } from "react-native";
import {
  colors,
  typography,
  spacing,
  borderRadius,
} from "../../public/styles/global";

export const styles = StyleSheet.create({
  screenBg: {
    flex: 1,
    backgroundColor: "#f0f0f0",
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing.xxl,
  },

  carouselWrap: {
    marginHorizontal: spacing.md,
    marginTop: 50,
    marginBottom: spacing.md,
  },
  carouselCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    minHeight: 280,
    overflow: "hidden",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  carouselBgImg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
  },

  imgAuthorBadge: {
    position: "absolute",
    top: spacing.sm,
    left: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    zIndex: 2,
  },
  imgAuthorName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  imgAuthorDate: {
    fontSize: 10,
    color: "rgba(255,255,255,0.7)",
    marginTop: 1,
  },

  cardLogo: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
    width: 56,
    height: 56,
    borderRadius: 14,
    zIndex: 2,
  },
  colorCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: spacing.md,
    paddingBottom: 0,
  },
  colorAuthorName: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  colorAuthorDate: {
    fontSize: 10,
    color: colors.textMuted,
    marginTop: 1,
  },
  colorBody: {
    ...typography.body,
    color: colors.textSecondary,
    lineHeight: 22,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xxl,
    paddingBottom: 72,
  },
  readMore: {
    position: "absolute",
    right: spacing.md,
    bottom: 56,
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
  },

  carouselFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.75)",
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  carouselFooterTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  dotsRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: spacing.sm,
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  dotActive: {
    backgroundColor: colors.primary,
    width: 20,
  },

  sectionTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    marginBottom: spacing.md,
  },
  quickActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: spacing.md,
    gap: spacing.md,
  },
  actionCard: {
    width: "47%",
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  actionIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.sm,
  },
  actionImg: {
    width: 32,
    height: 32,
    resizeMode: "contain",
  },
  actionEmoji: {
    fontSize: 28,
  },
  actionTitle: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: "600",
    textAlign: "center",
  },

  fab: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.xl,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.info,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  fabText: {
    fontSize: 28,
    color: "#fff",
    lineHeight: 30,
  },
});
