import { StyleSheet } from "react-native";
import { colors, typography, spacing, borderRadius } from "../../../public/styles/global";

const ACCENT = "#10b981";
const PLAYER_BG = "#050505";
const PLAYER_TEXT = "#d4d4d8";

export const devotionalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { flex: 1, paddingHorizontal: spacing.md },

  loading: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { ...typography.body, color: colors.textMuted, marginTop: spacing.md },

  // ---- Tab bar intern ----
  tabBar: {
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  tabItem: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabItemActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  tabText: { ...typography.caption, color: colors.textSecondary, fontWeight: "700" },
  tabTextActive: { color: colors.textInverse },

  // ---- Carduri intro / pasi ----
  introCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  introTitle: { ...typography.h3, color: colors.textPrimary },
  introDesc: { ...typography.bodySmall, color: colors.textMuted, marginTop: spacing.xs },

  stepLabel: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },

  chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  chip: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dayChip: {
    width: 44,
    alignItems: "center",
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  readonlyChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.borderLight,
  },
  chipActive: { backgroundColor: ACCENT, borderColor: ACCENT },
  chipText: { ...typography.caption, color: colors.textSecondary, fontWeight: "700" },
  chipTextActive: { color: colors.textInverse },

  optRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  optCard: {
    flexGrow: 1,
    flexBasis: "45%",
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surface,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  optCardActive: { backgroundColor: ACCENT, borderColor: ACCENT },
  optCardText: { ...typography.body, color: colors.textPrimary, fontWeight: "700" },
  optCardTextActive: { color: colors.textInverse },

  freqCard: {
    width: 60,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surface,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  freqNum: { ...typography.h3, color: colors.textPrimary },
  freqUnit: { ...typography.caption, color: colors.textMuted },

  helperNote: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm },
  errorNote: { ...typography.caption, color: colors.error, marginTop: spacing.md },
  noteSoft: {
    ...typography.caption,
    color: colors.textMuted,
    marginTop: spacing.sm,
    fontStyle: "italic",
  },

  startBtn: {
    backgroundColor: ACCENT,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    marginTop: spacing.xl,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  startBtnDisabled: { opacity: 0.5 },
  startBtnText: { ...typography.h3, color: colors.textInverse, fontWeight: "800" },

  skipBtn: { alignItems: "center", paddingVertical: spacing.md, marginTop: spacing.sm },
  skipBtnText: { ...typography.bodySmall, color: colors.textMuted, fontWeight: "600" },

  // ---- Personale / stats ----
  emptyPersonal: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing.xl },
  emptyTitle: { ...typography.h3, color: colors.textPrimary, marginBottom: spacing.sm },
  statCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  statLabel: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statBig: { ...typography.h1, color: colors.textPrimary, marginTop: spacing.xs },
  statScore: { ...typography.bodySmall, color: ACCENT, fontWeight: "700", marginTop: spacing.sm },
  progressTrack: {
    height: 10,
    borderRadius: borderRadius.full,
    backgroundColor: colors.border,
    marginTop: spacing.md,
    overflow: "hidden",
  },
  progressFill: { height: 10, borderRadius: borderRadius.full, backgroundColor: ACCENT },
  chartCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: "center",
  },
  deleteBtn: {
    marginTop: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1.5,
    borderColor: colors.error,
    alignItems: "center",
  },
  deleteBtnText: { ...typography.body, color: colors.error, fontWeight: "700" },

  // ---- Notificari ----
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.lg,
    marginBottom: spacing.sm,
  },
  stepBtn: {
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  stepBtnText: { fontSize: 26, color: colors.textPrimary, fontWeight: "700" },
  timeValue: { fontSize: 40, fontFamily: "Raleway", color: colors.textPrimary, fontWeight: "700", minWidth: 120, textAlign: "center" },
  reminderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  reminderTime: { ...typography.h3, color: colors.textPrimary },
  reminderDays: { ...typography.caption, color: colors.textMuted, marginTop: 2 },
  reminderDelete: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  reminderDeleteText: { ...typography.bodySmall, color: colors.error, fontWeight: "700" },

  // ---- Player overlay (negru, text gri medium) ----
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: PLAYER_BG,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  overlayTimer: {
    fontSize: 92,
    fontFamily: "Raleway",
    color: PLAYER_TEXT,
    fontWeight: "500",
    letterSpacing: 3,
  },
  overlayTimerLandscape: { fontSize: 120 },
  overlayTrack: {
    ...typography.body,
    color: "rgba(212,212,216,0.55)",
    marginTop: spacing.md,
    textAlign: "center",
    paddingHorizontal: spacing.xl,
  },
  controlsWrap: { alignItems: "center" },
  overlayHint: {
    position: "absolute",
    ...typography.caption,
    color: "rgba(212,212,216,0.3)",
    textAlign: "center",
    paddingHorizontal: spacing.xl,
  },

  // ---- Controale player (widget fin) ----
  ctrlPause: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 1.5,
    borderColor: "rgba(212,212,216,0.25)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  ctrlPauseIcon: { fontSize: 26, color: PLAYER_TEXT, letterSpacing: 2 },
  ctrlPauseLabel: { ...typography.caption, color: "rgba(212,212,216,0.6)", marginTop: 4 },
  ctrlRow: { flexDirection: "row", gap: spacing.md },
  ctrlResume: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.full,
    backgroundColor: ACCENT,
  },
  ctrlResumeText: { ...typography.body, color: "#fff", fontWeight: "700" },
  ctrlStop: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.full,
    borderWidth: 1.5,
    borderColor: "rgba(212,212,216,0.35)",
  },
  ctrlStopText: { ...typography.body, color: PLAYER_TEXT, fontWeight: "700" },
});
