import { StyleSheet } from "react-native";
import { colors, typography, spacing, borderRadius } from "../../../public/styles/global";

const ACCENT = "#10b981";
const PLAYER_BG = "#050505";
const PLAYER_TEXT = "#d4d4d8";

export const devotionalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { flex: 1, paddingHorizontal: spacing.md },

  loading: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { ...typography.body, color: colors.textMuted, marginTop: spacing.md },

  // ---- Tab bar intern ----
  tabBar: {
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  tabItem: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabItemActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  tabText: { ...typography.caption, color: colors.textSecondary, fontWeight: "700" },
  tabTextActive: { color: colors.textInverse },

  // ---- Carduri intro / pasi ----
  introCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  introTitle: { ...typography.h3, color: colors.textPrimary },
  introDesc: { ...typography.bodySmall, color: colors.textMuted, marginTop: spacing.xs },

  stepLabel: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },

  chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  chip: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dayChip: {
    width: 44,
    alignItems: "center",
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  readonlyChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.borderLight,
  },
  chipActive: { backgroundColor: ACCENT, borderColor: ACCENT },
  chipText: { ...typography.caption, color: colors.textSecondary, fontWeight: "700" },
  chipTextActive: { color: colors.textInverse },

  optRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  optCard: {
    flexGrow: 1,
    flexBasis: "45%",
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surface,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  optCardActive: { backgroundColor: ACCENT, borderColor: ACCENT },
  optCardText: { ...typography.body, color: colors.textPrimary, fontWeight: "700" },
  optCardTextActive: { color: colors.textInverse },

  freqCard: {
    width: 60,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surface,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  freqNum: { ...typography.h3, color: colors.textPrimary },
  freqUnit: { ...typography.caption, color: colors.textMuted },

  helperNote: { ...typography.caption, color: colors.textMuted, marginTop: spacing.sm },
  errorNote: { ...typography.caption, color: colors.error, marginTop: spacing.md },
  noteSoft: {
    ...typography.caption,
    color: colors.textMuted,
    marginTop: spacing.sm,
    fontStyle: "italic",
  },

  startBtn: {
    backgroundColor: ACCENT,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    marginTop: spacing.xl,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  startBtnDisabled: { opacity: 0.5 },
  startBtnText: { ...typography.h3, color: colors.textInverse, fontWeight: "800" },

  skipBtn: { alignItems: "center", paddingVertical: spacing.md, marginTop: spacing.sm },
  skipBtnText: { ...typography.bodySmall, color: colors.textMuted, fontWeight: "600" },

  // ---- Personale / stats ----
  emptyPersonal: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing.xl },
  emptyTitle: { ...typography.h3, color: colors.textPrimary, marginBottom: spacing.sm },
  statCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  statLabel: {
    ...typography.caption,
    color: colors.textSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statBig: { ...typography.h1, color: colors.textPrimary, marginTop: spacing.xs },
  statScore: { ...typography.bodySmall, color: ACCENT, fontWeight: "700", marginTop: spacing.sm },
  progressTrack: {
    height: 10,
    borderRadius: borderRadius.full,
    backgroundColor: colors.border,
    marginTop: spacing.md,
    overflow: "hidden",
  },
  progressFill: { height: 10, borderRadius: borderRadius.full, backgroundColor: ACCENT },
  chartCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: "center",
  },
  deleteBtn: {
    marginTop: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1.5,
    borderColor: colors.error,
    alignItems: "center",
  },
  deleteBtnText: { ...typography.body, color: colors.error, fontWeight: "700" },

  // ---- Notificari ----
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.lg,
    marginBottom: spacing.sm,
  },
  stepBtn: {
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  stepBtnText: { fontSize: 26, color: colors.textPrimary, fontWeight: "700" },
  timeValue: { fontSize: 40, fontFamily: "Raleway", color: colors.textPrimary, fontWeight: "700", minWidth: 120, textAlign: "center" },
  reminderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  reminderTime: { ...typography.h3, color: colors.textPrimary },
  reminderTitle: { ...typography.bodySmall, color: colors.textSecondary, fontWeight: "600", marginTop: 2 },
  reminderDays: { ...typography.caption, color: colors.textMuted, marginTop: 2 },

  // ---- Notificari: input custom + preview preset ----
  inputCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  inputHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.xs },
  inputLabel: { ...typography.caption, color: colors.textSecondary, fontWeight: "700" },
  charCount: { ...typography.caption, color: colors.textMuted },
  inputBox: {
    ...typography.body,
    color: colors.textPrimary,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  inputMultiline: { minHeight: 72, textAlignVertical: "top" },
  previewCard: {
    backgroundColor: colors.borderLight,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginTop: spacing.sm,
  },
  previewTitle: { ...typography.body, color: colors.textPrimary, fontWeight: "700" },
  previewBody: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 2 },

  // ---- Home (fundal negru) ----
  bg: { flex: 1 },
  quoteCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: spacing.lg,
    paddingTop: spacing.xl,
    marginTop: spacing.md,
  },
  quoteCopyBtn: { position: "absolute", top: spacing.md, right: spacing.md, zIndex: 2 },
  quoteMark: { fontSize: 40, color: "rgba(16,185,129,0.6)", fontFamily: "IMFellEnglish-Italic", marginBottom: -spacing.md },
  quoteText: { fontSize: 20, lineHeight: 30, color: "#e5e7eb", fontFamily: "IMFellEnglish-Italic" },
  quoteAuthor: { ...typography.bodySmall, color: "rgba(229,231,235,0.6)", textAlign: "right", marginTop: spacing.md, fontStyle: "italic" },

  bigBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    backgroundColor: ACCENT,
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.xl,
    marginTop: spacing.lg,
  },
  bigBtnGhost: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: ACCENT },
  bigBtnDone: { backgroundColor: "rgba(16,185,129,0.12)" },
  bigBtnText: { ...typography.h3, color: "#fff", fontWeight: "800" },

  // ---- Meniu mic (copy/share, actiuni card) ----
  menuBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "center", alignItems: "center", padding: spacing.xl },
  menuSheet: { backgroundColor: "#1f2937", borderRadius: borderRadius.lg, width: "100%", maxWidth: 320, paddingVertical: spacing.sm },
  menuHeader: { ...typography.caption, color: "rgba(255,255,255,0.5)", paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  menuItem: { flexDirection: "row", alignItems: "center", gap: spacing.md, paddingHorizontal: spacing.lg, paddingVertical: spacing.md },
  menuItemText: { ...typography.body, color: "#e5e7eb", fontWeight: "600" },
  menuDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.08)", marginHorizontal: spacing.md },

  // ---- Bottom sheet (setup rugaciune / task) ----
  sheetBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)", justifyContent: "flex-end" },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  sheetHandle: { alignSelf: "center", width: 44, height: 5, borderRadius: 3, backgroundColor: colors.border, marginBottom: spacing.md },
  sheetTitle: { ...typography.h3, color: colors.textPrimary, marginBottom: spacing.sm },
  taskEditRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },

  // ---- Icon picker ----
  pickerContainer: { flex: 1, backgroundColor: colors.background, paddingTop: spacing.xxl },
  pickerHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md, paddingVertical: spacing.md },
  pickerTitle: { ...typography.h3, color: colors.textPrimary },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
  },
  searchInput: { flex: 1, ...typography.body, color: colors.textPrimary, padding: 0 },
  pickerCategory: { ...typography.caption, color: colors.textSecondary, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.5, marginTop: spacing.lg, marginBottom: spacing.sm, marginHorizontal: spacing.md },
  iconGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, paddingHorizontal: spacing.md },
  iconCell: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },

  // ---- Culori ----
  swatchRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.xs },
  swatch: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" },
  swatchActive: { borderWidth: 2, borderColor: "#fff" },

  // ---- Builder ----
  builderHeaderRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.md },
  taskIconBtn: { width: 56, height: 56, borderRadius: borderRadius.lg, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },
  taskRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.borderLight },
  taskDot: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  taskTitle: { ...typography.body, color: colors.textPrimary, fontWeight: "600" },
  taskMeta: { ...typography.caption, color: colors.textMuted, marginTop: 2 },
  suggestionChip: { flexDirection: "row", alignItems: "center", gap: spacing.xs, backgroundColor: colors.surface, borderRadius: borderRadius.full, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  suggestionText: { ...typography.caption, color: colors.textSecondary, fontWeight: "600" },
  addCustomBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.xs, paddingVertical: spacing.md, marginTop: spacing.sm },
  addCustomText: { ...typography.body, fontWeight: "700" },

  // ---- Card devotional + liste ----
  devCard: { flexDirection: "row", alignItems: "center", gap: spacing.md, backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1.5, borderColor: colors.borderLight },
  devCardDefault: { borderColor: "#10b981" },
  devCardIcon: { width: 48, height: 48, borderRadius: borderRadius.md, alignItems: "center", justifyContent: "center" },
  devCardName: { ...typography.body, color: colors.textPrimary, fontWeight: "700" },
  devCardMeta: { ...typography.caption, color: colors.textMuted, marginTop: 2 },
  defaultBadge: { flexDirection: "row", alignItems: "center", gap: 3 },
  defaultBadgeText: { ...typography.caption, color: "#10b981", fontWeight: "700" },
  listHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.lg },
  newBtn: { flexDirection: "row", alignItems: "center", gap: 3, backgroundColor: ACCENT, borderRadius: borderRadius.full, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
  newBtnText: { ...typography.caption, color: "#fff", fontWeight: "700" },
  shareRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: "rgba(16,185,129,0.08)", borderRadius: borderRadius.lg, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: "rgba(16,185,129,0.3)" },
  shareAccept: { backgroundColor: ACCENT, borderRadius: borderRadius.full, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  shareAcceptText: { ...typography.caption, color: "#fff", fontWeight: "700" },
  shareDecline: { padding: spacing.sm },

  // ---- Share: user search ----
  userRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.borderLight },
  userAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.borderLight, alignItems: "center", justifyContent: "center" },
  userName: { ...typography.body, color: colors.textPrimary, fontWeight: "600", flex: 1 },

  // ---- Personale hub ----
  hubRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.borderLight },
  hubIcon: { width: 44, height: 44, borderRadius: borderRadius.md, backgroundColor: "rgba(16,185,129,0.12)", alignItems: "center", justifyContent: "center" },
  hubTitle: { ...typography.body, color: colors.textPrimary, fontWeight: "700" },
  hubDesc: { ...typography.caption, color: colors.textMuted, marginTop: 2 },

  // ---- Runner devotional ----
  runnerStep: { ...typography.body, color: "rgba(212,212,216,0.5)", marginBottom: spacing.lg, letterSpacing: 2 },
  runnerIcon: { width: 140, height: 140, borderRadius: 70, alignItems: "center", justifyContent: "center", marginBottom: spacing.xl },
  runnerTitle: { ...typography.h2, color: "#e5e7eb", textAlign: "center", paddingHorizontal: spacing.xl },
  runnerTimer: { fontSize: 56, fontFamily: "Raleway", color: "#d4d4d8", fontWeight: "500", marginTop: spacing.md },
  reminderDelete: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  reminderDeleteText: { ...typography.bodySmall, color: colors.error, fontWeight: "700" },

  // ---- Player overlay (negru, text gri medium) ----
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: PLAYER_BG,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  overlayTimer: {
    fontSize: 92,
    fontFamily: "Raleway",
    color: PLAYER_TEXT,
    fontWeight: "500",
    letterSpacing: 3,
  },
  overlayTrack: {
    ...typography.body,
    color: "rgba(212,212,216,0.55)",
    marginTop: spacing.md,
    textAlign: "center",
    paddingHorizontal: spacing.xl,
  },
  controlsWrap: { alignItems: "center" },
  overlayHint: {
    position: "absolute",
    ...typography.caption,
    color: "rgba(212,212,216,0.3)",
    textAlign: "center",
    paddingHorizontal: spacing.xl,
  },

  // ---- Controale player (widget fin) ----
  ctrlPause: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 1.5,
    borderColor: "rgba(212,212,216,0.25)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  ctrlPauseIcon: { fontSize: 26, color: PLAYER_TEXT, letterSpacing: 2 },
  ctrlPauseLabel: { ...typography.caption, color: "rgba(212,212,216,0.6)", marginTop: 4 },
  ctrlRow: { flexDirection: "row", gap: spacing.md },
  ctrlResume: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.full,
    backgroundColor: ACCENT,
  },
  ctrlResumeText: { ...typography.body, color: "#fff", fontWeight: "700" },
  ctrlStop: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.full,
    borderWidth: 1.5,
    borderColor: "rgba(212,212,216,0.35)",
  },
  ctrlStopText: { ...typography.body, color: PLAYER_TEXT, fontWeight: "700" },
});
